/**
 * @dev UserEntry interface corresponding to the entries within `users_wallets_referrals`
 * This structure is generated by TAN backend and is used to construct `Users` and `Referrals`
 */
export default interface UserEntry {
  user_id: string;
  polygon_wallet_address: string;
  referral_code: string;
  referred_by_user_id: string;
  referred_user_ids: string;
}
